
language: generic
sudo: required
dist: trusty

os:
  - linux
  - osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo apt-get update -qq         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo apt-get install -qq -y fpc ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install fpc           ; fi
  
script:
  - fpc hello.pp 
  - ./hello

notifications:
  email:
    on_success: false
    on_failure: change
