
language: generic
sudo: required
dist: trusty

os:
  - linux
  - osx
  - windows

install:
  - 'echo "OS: ${TRAVIS_OS_NAME}"'
  
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then 
        sudo apt-get update -qq;
        sudo apt-get install -qq -y fpc; 
    else
        if [ ${TRAVIS_OS_NAME} == "osx" ]; then 
            brew install fpc caskroom/cask/brew-cask;
            brew cask install fpcsrc; 
        else
            if [ ${TRAVIS_OS_NAME} == "windows" ]; then 
            fi
        fi
    fi
  
script:
  - fpc hello.pp 
  - ./hello

notifications:
  email:
    on_success: false
    on_failure: change
