language: c

jobs:
  include:
  - os: linux
    dist: focal
  - os: osx
    osx_image: xcode12.2

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update > /dev/null;
        brew install fpc > /dev/null;
      elif [[ $TRAVIS_OS_NAME == linux ]]; then
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe";
        sudo add-apt-repository "deb http://ftp.debian.org/debian experimental main contrib non-free";
        sudo apt-get update;
        sudo apt -q -t experimental install fpc;
      fi

install:
  - fpc -iV
  - fpc hello.pp
  
script:
  - ./hello
  
